trigger:
- master

pool:
  name: Local-agent-pool

stages:

- stage: Build
  displayName: Build Stage
  jobs:
  - job: BuildJob
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'compile'
        javaHomeOption: 'Path'
        jdkDirectory: '/usr/lib/jvm/java-11-openjdk-amd64'

- stage: Test
  displayName: Test Stage
  dependsOn: Build
  jobs:
  - job: TestJob
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'test'
        javaHomeOption: 'Path'
        jdkDirectory: '/usr/lib/jvm/java-11-openjdk-amd64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'

- stage: Package
  displayName: Package Stage
  dependsOn: Test
  jobs:
  - job: PackageJob
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package -pl webapp -am'
        javaHomeOption: 'Path'
        jdkDirectory: '/usr/lib/jvm/java-11-openjdk-amd64'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: 'webapp/target'
        artifactName: 'drop'

- stage: Deploy
  displayName: Deploy Stage
  dependsOn: Package
  jobs:
  - deployment: DeployWeb
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:

         # Download artifact created in Package stage
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(Pipeline.Workspace)'

          # Optional debug step (helps verify artifact exists)
          - script: |
              echo "Downloaded artifact contents:"
              ls -R $(Pipeline.Workspace)/drop
            displayName: "Verify artifact"

          # Deploy WAR to Azure App Service
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'azure-service-connection'
              appName: 'my-java-app-demo'
              resourceGroupName: 'rg-devops-demo'
              package: '$(Pipeline.Workspace)/drop/*.war'
